databases:
  - name: logindb
    databaseName: logindb
    user: postgres_user
    plan: free

services:
  - type: web
    name: spring-boot-login
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: logindb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: logindb
          property: port
      - key: DB_NAME
        fromDatabase:
          name: logindb
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: logindb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: logindb
          property: password
